version: "3"
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/var/www/html"
      - "./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped
    depends_on:
      - php-fpm

  mariadb:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
    restart: unless-stopped

  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP Server Port
      - "8025:8025" # Web GUI Port
    restart: unless-stopped

  php-fpm:
    build: ./.docker/php/
    volumes:
      - "./:/var/www/html"
    ports:
      - "9000:9000"
    restart: unless-stopped
    links:
      - mariadb
      - redis
      - beanstalkd

volumes:
  dbdata:
  redisdata:
